postsubmits:
  halo-dev/test-infra:
    - name: post-test-infra-deploy-prow
      run_if_changed: '^(config/prow/cluster/|config/prow/Makefile$)'
      decorate: true
      branches:
        - ^main$
      max_concurrency: 1
      spec:
        serviceAccountName: deployer
        containers:
          - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20230111-cd1b3caf9c
            command:
              - make
            args:
              - -C
              - config/prow
              - deploy-prow

periodics:
  - cron: "17 * * * *"  # Every hour at 17 minutes past the hour
    name: ci-test-infra-label-sync
    labels:
      app: label-sync
    decorate: true
    spec:
      containers:
        - name: label-sync
          image: gcr.io/k8s-prow/label_sync:v20231103-74dcf8db5c
          command:
            - label_sync
          args:
            - --config=/etc/config/labels.yaml
            - --confirm=true
            - --orgs=halo-dev
            - --token=/etc/github/token
            - --endpoint=http://ghproxy.default.svc.cluster.local
            - --endpoint=https://api.github.com
            - --debug
          volumeMounts:
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: config
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: oauth
          secret:
            secretName: github-token
        - name: config
          configMap:
            name: label-config
